- assets:
  - credentials.sh
steps:
  - name: Update system
    plugin: Script
    script:
      - gem uninstall bundler
      - apt-get update
  - name: Install Imagemagick
    plugin: Script
    script:
      - apt-get install -y software-properties-common imagemagick
      - apt-add-repository -y ppa:brightbox/ruby-ng
      - apt-get update
  - name: Install Ruby 2.2
    plugin: Script
    script:
      - apt-get install -y ruby2.2 ruby2.2-dev
      - update-alternatives --config ruby
      - gem install bundler -v 1.7.9
  - name: Install Jekyll Dependencies
    plugin: Script
    script:
      - cd $SRC_DIR
      - bundle install --path vendor/bundle
  - name: Build Jekyll site
    plugin: Script
    script:
      - locale-gen en_US.UTF-8
      - LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 bundle exec jekyll build --destination=/var/www/html
  - plugin: Script
    name: Run visual comparision to test via backtrac.io and comment in Jira
    script: |
      echo '{"body": "Probo build at ' $BUILD_DOMAIN  >> comment.json
      echo ' and visual test at https://backtrac.io/node' >> comment.json
      curl --header 'x-api-key: 0f8ce8c48323a0f933af9a277877e6df' --request POST https://backtrac.io/api/project/66505/compare_custom --data '{"url1":"https://docs.probo.ci/","sn1_name":"Prod","url2":"'"$BUILD_DOMAIN"'","sn2_name":"Probo ","diff_name":"Prod vs Probo"}' | rev | awk -F , '{print $2}' | rev | awk -F \\ '{print $5 $6}' | tr -d '\"' >> comment.json
      echo '"}' >> comment.json
      source $ASSET_DIR/credentials.sh
      BRANCH_NAME=$(echo $BRANCH_NAME | awk '{match($0,"([aA-zZ]+)-([0-9]+)")} {print substr($0,RSTART,RLENGTH)}')
      curl -D- -u $JIRA_NAME:$JIRA_PASS -X POST --data @comment.json -H "Content-Type: application/json" https://jira.zivtech.com/rest/api/2/issue/$BRANCH_NAME/comment
