language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
notifications:
  slack:
    secure: Zy2szuaW1lRzQS+5vqCedBKiiYnK7HaffhU869cYIsfiOw27+033wQ67nUX89zI7LZWK+eLJLbe2yBT6qr/vyFXTU3FRXt+Wb5CTmWROQ1MMkj5dvPBcDkz5HOAu6xpzOAcElqFxL/Ptuh1s8WiC0+diIs5xYeus1Y1te1mzpTIVROVB3WmlWSIe2lqZIlGsUiwcCUSBPq+qLvJBCx0MZoBZFlJPmqRt3B9c7ozpf0GI5TCxLQEh/Bog5hFlss4M0MBdFkfd6aczY1AssOKsDMdHkR58pxq/XNWwKNWBGkw6iQ8/HCcbC+p6TCI1UdilgQMg9nhfVO6WG/61bRU2iEiOCvOKpc3GDu0If5M4UIiY5+IIFFK0+oz8hZZfQT1hW4tODNWn1WgCwTH9mx7M+6/jRq3zRxw8xhQzv0TkPP91DRrwVkG2j442WX7Hhr6gQMCAqUd7BkB0/8WBU9O0mMek4TDTXMOJGC9GhMEnL7MlSRGbaDjl904yB+veyWVZELkmQpCCDAnkXNV/H1A2pbNBNrqDmk7B74krZh2v1ypE0n1T6lyVYspctrya0z61r28YzL2WOmKJjTZ52AsT1FGUtRAgE7MYu5ZehdCNUlXrsWglvftZniA/XQvhHfvYO59itj/WD5VPXx8jk3jPFRlt0iUMrQ6FUpVZOYCJ5ks=
branches:
  only:
  - master
env:
  global:
    secure: hGgyBU+rgYB6cjKuKCvMSkua4/4X13uhh8mi8vgvEZhK+olyb66Mu4GSs6SP9NX06DdDmZo221v5m8j6ShYZ7uD09zsKSIdcpa/m4z6f2hvtWsI9IFniWYLNEF7E1oUhLHLsZMSuKRp0hxWdTvDcSrbtuk0Jj7q1L2CToh4dQUZpSkHseEh71+OZpAe4zItkdx+Yd0YbUw/huCix7m7jsuG0hWHJbCSjMqt/imR14Tj0LwHt3WoQ071mdfLgvI81UATbzPt7yXD8PlTCBRkzvPxurTjLm+qYPVUrNcJVnAdr/ya9zBcnw0xJ+DChSs9mIGtk3gwnLaWKZK6sljNaV71D9nDrfrFRd7uvJVmFYCUDNo3CpkwKC+WPeT+DWmwSwCQm4DNXkXTAQmKIc+OrFwRinHaHYf1GZ7oyvn1bRSf+Rgeqyu9PL4luwSktOQK9EbMDK9QGO/s4C2PNWuvvb1TJowRvcqjjt+pdPcdqunz1S0UwKMvCX3+GuWXCCUlO2CHhPn5Q0IBnqFnkPXaYeG4Anpz6mGn26Mn8nUUmakfKjW8IHJ9fiyW1IqRGPUn5AxCFaivFlcn2S3+L3nIttx8d0uQjTe0LeeWXOKz9EhSCdu8I1y77UQE6kChnyT9Tpw+N5St2EFax6KQoklXfT13Kx9H58kKOUHX0LF3cCB4=
